name: Publish Android

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  VERSION: 0.11.0-rc

jobs:
  publish_android_package:
    name: Publish Android Package to Github Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Determine package version
        run: |
          if [ "${{ github.event.action }}" == "closed" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "PACKAGE_VERSION=${{ env.VERSION }}-SNAPSHOT" >> "$GITHUB_ENV"
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26
          add-to-path: false
          link-to-sdk: true

      - name: Install Rust toolchain
        run: |
          rustup show
          rustup component add rustfmt clippy

      - name: Setup Rust toolchains
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add i686-linux-android
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: Gradle Wrapper
        run: |
          gradle wrapper

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle Publish Android Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAndroidReleasePublicationToGithubPackagesRepository -PzkVersion=${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
